# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('speed', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('timeID', models.IntegerField(db_index=True))
            ],
        ),
    ]
