# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCrowd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatus',
            name='timeID',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
