# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetCrowd', '0003_auto_20180314_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinesPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.FloatField()),
                ('start_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('frame_id', models.IntegerField()),
                ('coord_id', models.IntegerField()),
            ],
        ),
    ]
